#!/bin/bash
# shellcheck disable=SC1091,SC2154

source _common.sh

if [[ "$new_path" != "/" ]]; then
	ynh_die --message="QuestarrNG does not support URL subpaths. Choose the root of a dedicated domain."
fi

ynh_script_progression "Updating QuestarrNG's Nginx and application URL configuration..."
ynh_change_url_nginx_config
ynh_config_add_systemd
ynh_systemctl --service="$app" --action="restart"
questarrng_register_service

ynh_script_progression "QuestarrNG URL update completed"
