#!/bin/bash
# shellcheck disable=SC1091,SC2154

source _common.sh

ynh_script_progression "Installing QuestarrNG release files..."
ynh_setup_source --dest_dir="$install_dir"

questarrng_prepare_data
questarrng_build_app
questarrng_install_apprise
questarrng_prepare_service

ynh_script_progression "Starting QuestarrNG..."
questarrng_start_service
questarrng_register_service

ynh_script_progression "QuestarrNG installation completed"
